### ISSUE TITLE
Speed up initial website loading times

### ISSUE THREAD

**Issue by aileenzeng** [aileenzeng/sidewalk-docker#20]
Website gets stuck here for a few minutes:
```
website_1  | [info] Compiling 121 Scala sources and 1 Java source to /root/app/target/scala-2.10/classes...
```

**Comment by misaugstad** [comment]
I don't think this is something we are going to be able to improve. We need to compile the code no matter what :) This is actually our code that is compiling :green_heart:

**Comment by aileenzeng** [comment]
Aah okay :) closing this then!
