### ISSUE TITLE
test on linux

### ISSUE THREAD

**Issue by misaugstad** [aileenzeng/sidewalk-docker#23]

**Comment by misaugstad** [comment]
From my first test, the only difference I've found (and this should be documented in the README) is that `docker-compose` is not bundled with Docker on Linux, and has to be installed separately (https://docs.docker.com/compose/install/). @aileenzeng said that the version she was running was 1.21.1, and that is the version of docker-compose I used for my testing on Linux.

The setup worked for me on Linux btw!

**Comment by aileenzeng** [comment]
Hooray! Thanks for the catch -- the README is updated now.

Resolved in https://github.com/aileenzeng/sidewalk-docker/commit/9df8fefea537512fe9b2ed5e144a0b858f50198e
